### ISSUE TITLE
Field.ddb_dump assumes None -> None translation for all data_types

### ISSUE THREAD

**Issue by numberoverzero** [mathcamp/flywheel#18]
There probably aren't many types that would care, but I came across [this code](https://github.com/mathcamp/flywheel/blob/master/flywheel/fields/__init__.py#L184) while looking into attribute_names.

Any reason why None is always returning `None`, instead of delegating it to the `data_type.ddb_dump` call?  I'd expect most custom types to check None anyway, and it doesn't leave much room for Types that care.

Unless there's a strong case for not supporting custom load/dump for `None`, this condition should probably be removed.

    import uuid
    import dynamo3
    from flywheel import Field, Model, Engine
    from flywheel.fields.types import TypeDefinition, STRING

    class NonNullType(TypeDefinition):
        data_type = int
        ddb_data_type = STRING

        def coerce(self, value, force):
            return value

        def ddb_dump(self, value):
            if value is None:
                return ''
            return str(value)

        def ddb_load(self, value):
            if value == '':
                return None
            return int(value)

    class MyModel(Model):
        __metadata__ = {
            '_name': str(uuid.uuid4())
        }
        pkey = Field(data_type=NonNullType(), hash_key=True)

    dynamo = dynamo3.DynamoDBConnection.connect(...)
    engine = Engine(dynamo=dynamo)
    engine.register(MyModel)
    engine.create_schema()

    pk = None

    from_typedef = NonNullType().ddb_dump(pk)
    print(type(from_typedef))

    m = MyModel(pkey=pk)
    from_model = m.ddb_dump_field_('pkey')
    print(type(from_model))

    engine.sync(m)

And the output:

    Traceback (most recent call last):
      File "crossj.py", line 77, in <module>
        engine.sync(m)
      File "/home/crossj/ws/flywheel/flywheel/engine.py", line 615, in sync
        self.save(item, overwrite=False)
      File "/home/crossj/ws/flywheel/flywheel/engine.py", line 465, in save
        **expected)
      File "build/bdist.linux-x86_64/egg/dynamo3/connection.py", line 382, in put_item
      File "build/bdist.linux-x86_64/egg/dynamo3/connection.py", line 207, in call
      File "build/bdist.linux-x86_64/egg/dynamo3/exception.py", line 46, in raise_if_error
    dynamo3.exception.DynamoDBError: ValidationException: One or more parameter values were \
      invalid: Missing the key pkey in the item
    Args: {'expected': {'pkey': {'ComparisonOperator': 'NULL'}},
     'item': {},
     'return_consumed_capacity': 'NONE',
     'return_values': 'NONE',
     'table_name': '91f18196-2d5c-41c3-ad1e-15d8f007e6a8'}

**Comment by numberoverzero** [comment]
Closing this out since there haven't been any requests for the behavior.
